- name: run apt update if debian-based
  include_tasks: "snippets/apt_update.yaml"
- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_packages.common }}"
