- name: setup epel, oracle and rpmfusion repos
  include_tasks: extra_repos.yaml
  tags: 
   - epel_setup
   - rpmfusion_setup

- name: install basic quality of life packages (no display server required)
  include_tasks: basic_packages.yaml
  tags:
    - basic_packages
