- name: ensure podman and podman-related packages
  include: snippets/rpm-ostree-install.yaml
  vars:
    packages:
    - podman
    - skopeo
    - buildah
    - slirp4netns
    - python3-libselinux
    - python3-policycoreutils

- name: "create podman user, {{ podman_user }}"
  user:
    name: "{{ podman_user }}"
    state: present
    create_home: no

- name: create apps group
  group:
    name: "apps"
    state: present

- name: "create container appdata folder {{ container_data_dir }}"
  file:
    state: directory
    path: "{{ container_data_dir }}"
    owner: "{{ podman_user }}"
    group: "apps"
    mode: 0775
