- name: place prometheus service file (from template)
  template:
    src: templates/prometheus_service_file.j2
    dest: "/etc/systemd/system/prometheus.service"
    owner: root
    group: root
    mode: '0755'

- name: place node exporter service file (from template)
  template:
    src: templates/node_exporter_service_file.j2
    dest: "/etc/systemd/system/prometheus-node-exporter.service"
    owner: root
    group: root
    mode: '0755'

- name: reload systemd daemons
  systemd:
    daemon_reload: yes
