- name: start prometheus service
  service:
    name: prometheus
    enabled: yes
    state: restarted

- name: start node-exporter service
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: restarted
