- name: make /tmp/prometheus dir
  file:
    state: directory
    path: /tmp/prometheus
    mode: '0755'

- name: wipe out any old prometheus files in /tmp/
  file:
    path: "/tmp/prometheus"
    state: absent

- name: wipe out any old node-exporter files in /tmp/
  file:
    path: "/tmp/node-exporter"
    state: absent

- name: create /tmp/prometheus for "install"
  file:
    path: "/tmp/prometheus/"
    state: directory

- name: create /tmp/node-exporter for "install"
  file:
    path: "/tmp/node-exporter/"
    state: directory

- name: install prometheus
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
    extra_opts:
      - --strip-components=1

- name: install node-exporter
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: "/tmp/node-exporter"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
    extra_opts:
      - --strip-components=1

- name: install other os-family specific prometheus-related packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ prometheus_packages[ansible_facts.os_family] }}"
