- name: place prometheus config (from template)
  template:
    src: "templates/prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0755'
